### PR TITLE
Add new properties from recent releases

### PR DESCRIPTION
**Pull request by nchlswhttkr**
Hey! I've added a few properties introduced in recent releases, going off the docs and changelog.

* `if`, `key`, `depends_on` and `allow_dependency_failure` for all the basic steps (Command, Block, Wait, Trigger)
* `multiple` for Block steps using select fields

Some of these changes should probably be applied to "groupStep" definition as well, if you have any guidance there.

I haven't added the Input step either, it seems to be new and I'm not sure how finalised it is.

Cheers! :shipit:

### CODE REVIEW

**Comment by toolmantim** [comment]
Wow, thanks so much @nchlswhttkr. Really appreciate the time you put into updating this. I think we might need to add `allow_failure` to there too.

I think our step grouping is currently undocumented/unsupported at the moment (is that true @matthewd?) so perhaps we can ignore that for now?

**Comment by nchlswhttkr** [comment]
Good catch! I've added it.

**Comment by toolmantim** [comment]
Really appreciate it @nchlswhttkr ☺️

**Comment by nchlswhttkr** [comment]
My pleasure @toolmantim, my thanks to the team for the free plan for open source projects!

**Pull request merged**
