### PR TITLE
Add cancel_on_build_failing property for commnad step definition

### PR DESCRIPTION
**Pull request by amishra-uber**
Buildkite added new attribute called  `cancel_on_build_failing`. Added `cancel_on_build_failing` attribute to buildkite schema.

### CODE REVIEW

**Comment by jl-applied** [comment]
Closes https://github.com/buildkite/pipeline-schema/issues/48

**Comment by timriley** [comment]
Closing this in favour of #49; we'll be addressing that PR shortly. Thanks again and sorry to keep you waiting here!

**Comment by jl-applied** [comment]
@timriley I think this also intended to close https://github.com/buildkite/pipeline-schema/issues/37 which is missing from #49. Happy to send a patch to solely address https://github.com/buildkite/pipeline-schema/issues/37 as I am also interested in that change (though I suspect will just be this delta once that lands in `main`)

**Comment by mhaylock** [comment]
Thanks @jl-applied, we've merged #45 today which fixes #37 - I've closed that issue now, thanks for pointing it out.

**Comment by jl-applied** [comment]
Got it. Thanks all :+1:

**Pull request closed without merging**
